## 异常Exception

在 Python 中，可能会遇到3种错误：

1、语法错误(syntax error)

2、逻辑错误 (logic error bug)

3、异常 (exception)

#### 捕获异常 

* try、except、else、finally 配合使用

![image-20230321003604268](/Users/guojie/Notes/Python/images/image-20230321003604268.png)

* try：包含可能会产生异常的代码，一旦产生异常，会直接跳过try中剩余未执行的代码
* except：当出现异常时，会执行except中的代码，可以省略
* else：当没有出现异常时，会执行else中的代码，可以省略，只能在有except 时使用
* finally：不管是否出现异常，最终都会执行 finally 中的代码，可以省略

#### 常见(内置)异常类型

* ZeroDivisionError：0作为除数
* IndexError：索引超出正常范围
* NameError：无法找到名称(标识符)
* KeyError：无法找到字典的Key
* TypeError：使用了不恰当类型的对象
* ValueError：虽然类型正确，但值不正确
* AttributeError：操作(访问、赋值等)属性失败

#### 异常的传播

* 异常会由内往外传播出去，直到被拦截捕获或传播到全局作用域为止
* 当异常传播到全局作用域时，还没有被拦截捕获，就会导致程序终止运行，并将异常信息打印出来

#### 抛出异常

* 通过 raise 主动抛出异常

```python
class Person:
    def __init__(self):
        self.__age = 1
    @property
    def age(self):
        return self.__age

    @age.setter
    def age(self, age):
        if age < 1:
            raise ValueError('age不能小于1')
        if age > 120:
            raise ValueError('age不能大于120')
        self.__age = age

p1 = Person()
p1.age = -10
print(p1.age)
```

#### 自定义异常

* 自定义的异常类型，最终要继承自Exception 而不是BasicException

